improve error handling

diff --git a/xml-group-manager b/xml-group-manager
--- a/xml-group-manager
+++ b/xml-group-manager
@@ -6,7 +6,6 @@
 # the GNU General Public License (GPL), version 3, or at your option
 # any later version.
 
-
 script_usage()
 {
 echo "
@@ -90,11 +89,11 @@ add_group()
 		prepair_files
 		xsltproc --stringparam xmlfile $tmp_input_file --stringparam group-id "$group" $add_stylesheet $catalog > $tmp_catalog
 		if [[ $? != 0 ]]; then
-			rm $tmp_catalog $tmp_input_file
+			rm -- $tmp_catalog $tmp_input_file
 			exit 1
 		else
 			xmllint --format $tmp_catalog -o $catalog
-			rm $tmp_catalog $tmp_input_file
+			rm -- $tmp_catalog $tmp_input_file
 			exit 0
 		fi
 	else
@@ -109,11 +108,11 @@ delete_group()
 		prepair_file
 		xsltproc --stringparam group-id "$group" $delete_stylesheet $catalog > $tmp_catalog
 		if [[ $? != 0 ]]; then
-			rm $tmp_catalog
+			rm -- $tmp_catalog
 			exit 1
 		else
 			xmllint --format $tmp_catalog -o $catalog
-			rm $tmp_catalog
+			rm -- $tmp_catalog
 			exit 0
 		fi
 	else
@@ -128,11 +127,11 @@ update_group()
 		prepair_files
 		xsltproc --stringparam xmlfile $tmp_input_file --stringparam group-id "$group" $update_stylesheet $catalog > $tmp_catalog
 		if [[ $? != 0 ]]; then
-			rm $tmp_catalog $tmp_input_file
+			rm -- $tmp_catalog $tmp_input_file
 			exit 1
 		else
 			xmllint --format $tmp_catalog -o $catalog
-			rm $tmp_catalog $tmp_input_file
+			rm -- $tmp_catalog $tmp_input_file
 			exit 0
 		fi
 	else
@@ -192,6 +191,9 @@ while true; do
 				shift;
             fi
             ;;
+		--)
+			break;
+			;;
 		*)
 			break;
 			;;
@@ -211,5 +213,9 @@ case "$action" in
 	update)
 		init
 		update_group
+		;;
+	*)
+		echo "Error: No valid action given!"
+		exit 1
 		;;
 esac
